name: Update Version Date

on:
  push:
    branches:
      - master  # Change this to "master" if that's your main branch name
  pull_request:
    types:
      - closed

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Update version date
      run: |
        updated_date=$(date -u +"%Y-%m-%d")
        echo "Updating version date to $updated_date"
        jq --arg updated "$updated_date" '.updated = $updated' app-version.json > app-version-temp.json
        mv app-version-temp.json app-version.json
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "Update version date [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
