name: Update Version

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Version
        run: |
          # Update the "updated" field with the current date
          updated=$(date +%F)
          sed -i 's/"updated": "[^"]*"/"updated": "'"$updated"'"/' app-version.json

          # Commit and push the changes if needed
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update 'updated' field" || true
          git push origin master
